[versions]
lombok = "8.6"
paperweight = "2.0.0-beta.17"
run-paper = "2.3.1"
paper-yaml = "1.2.0"
shadow = "9.2.2"

minecraft = "1.21.5"
slf4j = "2.0.16"
checkerframework = "3.52.0"
jetbrains-annotations = "26.0.2"

assertj = "3.27.3"
junit-platform-launcher = "1.13.4"
junit = "5.11.4"
mockito = "5.15.2"
compile-testing = "0.23.0"

adventure-api = "4.21.0"

configurate = "4.2.0"

javapoet = "0.7.0"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }

guava = { module = "com.google.guava:guava", version = "33.4.8-jre" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-jackson = { module = "org.spongepowered:configurate-jackson", version.ref = "configurate" }

checkerframework = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }

javapoet = { module = "com.palantir.javapoet:javapoet", version.ref = "javapoet" }
compile-testing = { module = "com.google.testing.compile:compile-testing", version.ref = "compile-testing" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
resource-factory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "paper-yaml" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[bundles]
annotations = [
    "checkerframework",
    "jetbrains-annotations"
]
configurate = [
    "configurate-core",
    "configurate-yaml",
    "configurate-jackson"
]
test = [
    "junit-jupiter-api",
    "junit-jupiter-params",
    "mockito-junit-jupiter",
    "assertj-core",
    "slf4j-simple"
]
test-runtime = [
    "junit-platform-launcher",
    "junit-jupiter-engine",
]