[versions]
adventure-api = "4.21.0"
assertj = "3.27.3"

checkerframework = "3.52.0"
compile-testing = "0.23.0"
configurate = "4.2.0"

guava = "33.4.8-jre"

javapoet = "0.7.0"
jetbrains-annotations = "26.0.2"
junit = "5.11.4"
junit-platform-launcher = "1.13.4"

lombok = "8.6"

minecraft = "1.21.5"
mockito = "5.15.2"

paper-yaml = "1.2.0"
paperweight = "2.0.0-beta.17"

run-paper = "2.3.1"

shadow = "9.2.2"
slf4j = "2.0.16"

[libraries]
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure-api" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-api" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

checkerframework-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
compile-testing = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compile-testing" }
configurate-core = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurate-jackson = { group = "org.spongepowered", name = "configurate-jackson", version.ref = "configurate" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

javapoet = { group = "com.palantir.javapoet", name = "javapoet", version.ref = "javapoet" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }

mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }

resource-factory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "paper-yaml" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
